steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["clean", "package"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/tomcat-tomcat-3db004ef:$COMMIT_SHA", "-t", "gcr.io/${PROJECT_ID}/tomcat-tomcat-3db004ef:latest", "--build-arg=PETCLINIC_WAR_APP=apps/petclinic.war", "."]
images:
  - "gcr.io/${PROJECT_ID}/tomcat-tomcat-3db004ef:$COMMIT_SHA"
  - "gcr.io/${PROJECT_ID}/tomcat-tomcat-3db004ef:latest"
